### ISSUE TITLE
Look into PEBS

### ISSUE THREAD

**Issue by tilsche** [tud-zih-energy/lo2s#67] opened 2018-06-27 12:35 UTC
Can we use PEBS through perf_event with recent kernels?
Or maybe manually use PEBS? (https://github.com/andikleen/pmu-tools/tree/master/simple-pebs)

**Comment by cvonelm** [comment] 2019-05-07 16:20
As far as I have looked into it, perf from linux 5.0 already supports PEBS out of the box and will use it automatically if the given sampling event config supports it. (I haven't looked into older kernels, but this seems like a fairly new feature). Everything looks sound from a performance standpoint too (The internal kernel buffers are most likely big enough, and there are no unnecessary interrupts involved)

However there are 2 major problems currently:

1. There is no way to directly check if a given sampling config will use PEBS. Also there is no feasible way to infer it from the sampling config either, as whether or not PEBS will be used depends on at least a dozen factors. There is a X86_PERF_EVENT_LARGE_PEBS flag set for every sampling event config capable of using PEBS in the kernel, but there is no way to get it from the outside

**Comment by cvonelm** [comment] 2019-05-13 21:02
I've got in touch with the author of that patch, and he confirmed that this is a bug, he will fix it upstream and that we can use this patch in the mean time:
```diff
diff --git a/arch/x86/events/intel/core.c b/arch/x86/events/intel/core.c
index 416233f92b3c..8d4e215ab7a8 100644
--- a/arch/x86/events/intel/core.c
+++ b/arch/x86/events/intel/core.c
@@ -3280,7 +3306,7 @@ static int intel_pmu_hw_config(struct perf_event *event)
  return ret;
 
  if (event->attr.precise_ip) {
- if (!(event->attr.freq || event->attr.wakeup_events)) {
+ if (!(event->attr.freq || (event->attr.wakeup_events && !event->attr.watermark))) {
  event->hw.flags |= PERF_X86_EVENT_AUTO_RELOAD;
  if (!(event->attr.sample_type &
        ~intel_pmu_large_pebs_flags(event))) 
```

Furthermore I've looked into how we could do PEBS more explicitly in perf, sadly there is little to no precedence for feature tests in the perf interface. The most Linux way(tm) of doing this is probably a force_pebs perf_event_attr option which will makes the perf_event_open() call fail if the current config will not use PEBS (somewhat similar to how precise_ip works currently).

**Comment by cvonelm** [comment] 2019-05-22 08:01
Small Update:
Thanks to some help from @tilsche i was able to compile a linux kernel with a few debug printk's sprinkled into to probe lo2s' PEBS support

What I've found out so far
1. Timestamps (PERF_SAMPLE_TIME) are only available on Skylake or newer processors
2. We can not use use_clockid with PEBS, but thankfully the clocksource for PEBS samples is the TSC which should be equal to monotonic_raw
3. These limitations aside, lo2s seems to support PEBS

**Comment by cvonelm** [comment] 2019-05-22 18:09
I've run the tests now and it looks pretty promising for pebs:
![pebs](https://user-images.githubusercontent.com/17126443/58196731-3cb1c780-7ccb-11e9-8d4e-1de84a6a306e.png)

The raw data is here: [pebs_tests.csv.zip](https://github.com/tud-zih-energy/lo2s/files/3208663/pebs_tests.csv.zip)

I've ran 25 iterations of this lo2s the command line below:
```
# ./lo2s -c 650000 bt.B.x
```
As well as 25 iterations of bt.B.x as a reference

On a site note I've discovered that PEBS supports an approximately 2.6 times higher sample rate compared to non-PEBS before getting throttled

**Comment by tilsche** [comment] 2019-05-28 12:24
- Please retry experiments with `kernel.perf_cpu_time_max_percent = 0` and a lower sampling interval to get more significant results.

- Add comparison with similar `perf record`.

- Add "pebs" clock that uses `MONOTONIC_RAW` as clocksource within lo2s, but does *not* set a clockid for `perf_event_open`. If the offset detected by perf/time/converter is too high, it uses the offset, otherwise 0 is assumed.

**Comment by cvonelm** [comment] 2019-06-03 11:42
I've redone this with `perf_cpu_time_max_percent=0` and a 50000 sample rate

Here's the data: [pebs.csv.zip](https://github.com/tud-zih-energy/lo2s/files/3247316/pebs.csv.zip)

And here is something nice to look at:
![pebs](https://user-images.githubusercontent.com/17126443/58798747-b7e87700-8603-11e9-8ba6-e8ddd75b46d1.png)

With perf record I'm having problems running it from inside a script (in both python an sh)
Whenever I try to grab the stdout I perf segfaults

**Comment by cvonelm** [comment] 2019-06-13 13:14
Here's the graph for perf
![pebs](https://user-images.githubusercontent.com/17126443/59435411-cc8bf280-8ded-11e9-8364-3eaf295ffb42.png)

Heres the data for perf : [perf-pebs.csv.zip](https://github.com/tud-zih-energy/lo2s/files/3286184/perf-pebs.csv.zip)

**Comment by rschoene** [comment] 2019-06-13 13:43
@cvonelm What is the y-axis? milliseconds of runtime?

**Comment by cvonelm** [comment] 2019-06-13 14:11
Performance Points in the NAS Parallel Benchmark[1] I've used (higher is better)

[1] Benchmark specification BT, Benchmark class B

**Comment by bmario** [comment] 2019-06-17 10:52
#118 Added a special pebs clock. Everything else seems to be working just fine.

So I'm closing this issue as fixed.

**Closed by bmario** 2019-06-17 10:52 UTC
Labels: low priority
